# Generated by Django 5.0.4 on 2024-05-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ssn', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('page', models.CharField(blank=True, max_length=255)),
                ('phone', models.IntegerField()),
                ('company_logo', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
