# Generated by Django 5.0.4 on 2024-05-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='page',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
