# Generated by Django 5.0.4 on 2024-05-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_bio_alter_company_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ssn',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
