# Generated by Django 5.0.4 on 2024-05-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='page',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='ssn',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
